Metaheuristics: opp::TravellingSalesmanProblem Class Reference
opp::TravellingSalesmanProblem Class Reference
Representation of the Euclidean Travelling Salesman Problem.
#include <TravellingSalesmanProblem.hpp>
Public Member Functions
TravellingSalesmanProblem ()
Constructs a randomly generated Euclidean Travelling Salesman Problem.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
Solution select (const std::vector< Solution > &p) const
Selects a solution from the population using Tournament Selection.
std::pair< Solution, Solution > crossover (const Solution &pA, const Solution &pB) const
Applies Uniform Order Based Crossover on parent solutions.
int cost (const Solution &s) const
Calculates the cost of a solution.
Solution getOptimal () const
void setOptimal (const Solution &s)
Private Member Functions
void copyPreserved (const std::deque< bool > &b, const Solution &pA, const Solution &pB, Solution &cA, Solution &cB, std::deque< City > &vA, std::deque< City > &vB) const
Used in Crossover to copy the preserved elements of parents to children and determine the elements to be changed.
void reorder (const Solution &p, std::deque< City > &v, std::deque< City > &w) const
Used in Crossover to reorder the elements to be changed in respect to their order in the other parent.
void copyChanged (const std::deque< bool > &b, Solution &cA, Solution &cB, std::deque< City > &wA, std::deque< City > &wB) const
Used in Crossover to copy the changed elements of parents to children after reordering.
Private Attributes
int sz
The size of the problem, that is the number of cities.
int trmMax
The number of participants in a tournament for selection.
std::vector< std::vector< int > > distanceMatrix
The matrix representing distances between cities.
Solution optimal
The initially generated solution to the problem and its cities.
Static Private Attributes
static constexpr SDL_Rect boundingBox = {100, 60, 960, 960}
The bounds of the problem.
static thread_local std::random_device rd {}
The random device used to generate a seed for the random number generator.
static thread_local std::mt19937 rng {rd()}
The random number generator used to generate problems and implement stochastic functionality.
Detailed Description
Representation of the Euclidean Travelling Salesman Problem.
Author
Luke Sell
Definition at line 19 of file TravellingSalesmanProblem.hpp.
Member Function Documentation
copyChanged()
void TravellingSalesmanProblem::copyChanged (const std::deque< bool > & b, Solution & cA, Solution & cB, std::deque< City > & wA, std::deque< City > & wB) const private
Used in Crossover to copy the changed elements of parents to children after reordering.
Parameters
b Is the bit string used to crossover.
cA Is the first child.
cB Is the second child.
wA Is the first reordered list of elements to be changed.
wB Is the second reordered list of elements to be changed.
Definition at line 138 of file TravellingSalesmanProblem.cpp.
         {
   for (Uint32 i = 0; i < b.size(); ++i) {
     if (b[i]) {
       cB.order[i] = wB[0];
       wB.pop_front();
     } else {
       cA.order[i] = wA[0];
       wA.pop_front();
     }
   }
 }
References opp::Solution::order.
Referenced by crossover().
copyPreserved()
void TravellingSalesmanProblem::copyPreserved (const std::deque< bool > & b, const Solution & pA, const Solution & pB, Solution & cA, Solution & cB, std::deque< City > & vA, std::deque< City > & vB) const private
Used in Crossover to copy the preserved elements of parents to children and determine the elements to be changed.
Parameters
b Is the bit string used to crossover.
pA Is the first parent.
pB Is the second parent.
cA Is the first child.
cB Is the second child.
vA Is the first list of elements to be changed.
vB Is the second list of elements to be changed.
Definition at line 112 of file TravellingSalesmanProblem.cpp.
         {
   for (Uint32 i = 0; i < b.size(); ++i) {
     if (b[i]) {
       cA.order[i] = pA.order[i];
       vB.push_back(pB.order[i]);
     } else {
       cB.order[i] = pB.order[i];
       vA.push_back(pA.order[i]);
     }
   }
 }
References opp::Solution::order.
Referenced by crossover().
cost()
int TravellingSalesmanProblem::cost (const Solution & s) const
Calculates the cost of a solution.
Parameters
s Is the solution to calculate the cost for.
Returns
The cost of the solution.
Definition at line 181 of file TravellingSalesmanProblem.cpp.
{
   int c = 0;
   // Calculate cost of solution
   for (Uint32 i = 0; i < s.order.size() - 1; ++i) {
     c += distanceMatrix[s.order[i].name][s.order[i + 1].name];
   }
   c += distanceMatrix[s.order[s.order.size() - 1].name][s.order[0].name];
   return c;
 }
References distanceMatrix, and opp::Solution::order.
Referenced by crossover(), and randomSolution().
crossover()
std::pair< Solution, Solution > TravellingSalesmanProblem::crossover (const Solution & pA, const Solution & pB) const
Applies Uniform Order Based Crossover on parent solutions.
Parameters
pA Is the first parent.
pB Is the second parent.
Returns
The pair of children generated.
Definition at line 154 of file TravellingSalesmanProblem.cpp.
{
   auto cA = pA;
   auto cB = pB;
   std::deque<City> vA, vB, wA, wB;
   std::deque<bool> b(pA.order.size());
   std::uniform_int_distribution<int> ud{0, 1};
   // Generate random bit string
   std::generate(b.begin(), b.end(), [&ud] {
     return !!ud(rng);
   });
   // Perform Crossover
   copyPreserved(b, pA, pB, cA, cB, vA, vB);
   reorder(pA, vB, wB);
   reorder(pB, vA, wA);
   copyChanged(b, cA, cB, wA, wB);
   // Update cost of solutions
   cA.cost = cost(cA);
   cB.cost = cost(cB);
   return {cA, cB};
 }
References copyChanged(), copyPreserved(), cost(), opp::Solution::order, reorder(), and rng.
Referenced by mh::Metaheuristic::crossover().
generateMove()
Move TravellingSalesmanProblem::generateMove (const Solution & s) const
Generates a move from the neighbourhood of a solution.
Parameters
s Is the solution to generate a move for.
Returns
The move generated.
Definition at line 33 of file TravellingSalesmanProblem.cpp.
{
   std::uniform_int_distribution<int> ud{0, sz - 1};
   int x, y;
   // Generate move from neighbourhood
   do {
     x = ud(rng);
     y = ud(rng);
   } while (x == y);
   // Deterministic ordering
   if (x > y) {
     std::swap(x, y);
   }
   return {s.order[y].name, x, s.order[x].name, y};
 }
References opp::Solution::order, rng, and sz.
Referenced by mh::Metaheuristic::generateMove(), and mh::Metaheuristic::neighbour().
neighbour()
Solution TravellingSalesmanProblem::neighbour (const Solution & s, const Move & m) const
Applies a move to a solution.
Parameters
s Is the solution to apply the move to.
m Is the move to apply.
Returns
The neighbouring solution.
Definition at line 51 of file TravellingSalesmanProblem.cpp.
{
   auto t = s;
   // Apply move to solution
   t.order[m.indexA] = s.order[m.indexB];
   t.order[m.indexB] = s.order[m.indexA];
   t.moveMade = m;
   // Calculate updated cost of solution efficiently
   // Handle left edge of B
   t.cost -= distanceMatrix[m.cityA][s.order[m.indexB - 1].name];
   t.cost += distanceMatrix[m.cityB][t.order[m.indexB - 1].name];
   // Handle right edge of B, with potential for last element
   if (m.indexB != sz - 1) {
     t.cost -= distanceMatrix[m.cityA][s.order[m.indexB + 1].name];
     t.cost += distanceMatrix[m.cityB][t.order[m.indexB + 1].name];
   } else {
     t.cost -= distanceMatrix[m.cityA][s.order[0].name];
     t.cost += distanceMatrix[m.cityB][t.order[0].name];
   }
   // Handle left edge of A, with potential for first element
   if (m.indexA != 0) {
     t.cost -= distanceMatrix[m.cityB][s.order[m.indexA - 1].name];
     t.cost += distanceMatrix[m.cityA][t.order[m.indexA - 1].name];
   } else {
     t.cost -= distanceMatrix[m.cityB][s.order[s.order.size() - 1].name];
     t.cost += distanceMatrix[m.cityA][t.order[t.order.size() - 1].name];
   }
   // Handle right edge of A
   t.cost -= distanceMatrix[m.cityB][s.order[m.indexA + 1].name];
   t.cost += distanceMatrix[m.cityA][t.order[m.indexA + 1].name];
   return t;
 }
References opp::Move::cityA, opp::Move::cityB, distanceMatrix, opp::Move::indexA, opp::Move::indexB, opp::Solution::order, and sz.
Referenced by mh::Metaheuristic::neighbour().
randomSolution()
Solution TravellingSalesmanProblem::randomSolution () const
Generates a random solution to the problem.
Returns
The random solution.
Definition at line 90 of file TravellingSalesmanProblem.cpp.
{
   auto t = optimal;
   std::shuffle(t.order.begin(), t.order.end(), rng);
   t.cost = cost(t);
   return t;
 }
References opp::Solution::cost, cost(), optimal, and rng.
Referenced by mh::Metaheuristic::randomSolution().
reorder()
void TravellingSalesmanProblem::reorder (const Solution & p, std::deque< City > & v, std::deque< City > & w) const private
Used in Crossover to reorder the elements to be changed in respect to their order in the other parent.
Parameters
p Is the other parent to be used.
v Is the list of elements to be changed.
w Is the reordered list of elements to be changed.
Definition at line 129 of file TravellingSalesmanProblem.cpp.
{
   for (const auto& city : p.order) {
     if (std::find(v.begin(), v.end(), city) != v.end()) {
       w.push_back(city);
     }
   }
 }
References opp::Solution::order.
Referenced by crossover().
select()
Solution TravellingSalesmanProblem::select (const std::vector< Solution > & p) const
Selects a solution from the population using Tournament Selection.
Parameters
p Is the population to select from.
Returns
The selected solution.
Definition at line 97 of file TravellingSalesmanProblem.cpp.
{
   std::uniform_int_distribution<Uint32> ud{0, p.size() - 1};
   auto optimalS = p[ud(rng)];
   // Hold Tournament
   for (int i = 0; i < trmMax - 1; ++i) {
     auto t = p[ud(rng)];
     if (t.cost < optimalS.cost) {
       optimalS = t;
     }
   }
   return optimalS;
 }
References rng, and trmMax.
Referenced by mh::Metaheuristic::crossover().
The documentation for this class was generated from the following files:
TravellingSalesmanProblem.hpp
TravellingSalesmanProblem.cpp