Metaheuristics: mh::TabuSearch Class Reference
mh::TabuSearch Class Reference
Represents the use of Tabu Search to solve a problem.
#include <TabuSearch.hpp>
Public Member Functions
TabuSearch (const TabuSearch &)=delete
TabuSearch & operator= (const TabuSearch &)=delete
TabuSearch (const Tsp &t)
Constructs the Tabu Search with the problem to be solved and search parameters.
Move generateMove (const Solution &s, const std::list< Move > &tabuList) const
Generates a move from the neighbourhood of a solution, that is not tabu.
Solution findOptimal () const override
Finds a near optimal solution to the problem using Tabu Search.
Public Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Metaheuristic &)=delete
Metaheuristic & operator= (const Metaheuristic &)=delete
Private Types
using Tsp = opp::TravellingSalesmanProblem
using Move = opp::Move
using Solution = opp::Solution
Private Attributes
const int lclMax
The number of times to use local search for.
const int nbrMax
The number of neighbours to consider when gradient sampling.
const Uint32 tabuMax
The maximum number of moves that are considered tabu at any one time.
Additional Inherited Members
Protected Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Tsp &t)
Constructs a metaheuristic with the problem to be solved.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s) const
Applies a move to a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
std::pair< Solution, Solution > crossover (const std::vector< Solution > &p) const
Applies Uniform Order Based Crossover on parent solutions.
Detailed Description
Represents the use of Tabu Search to solve a problem.
Author
Luke Sell
Definition at line 17 of file TabuSearch.hpp.
Constructor & Destructor Documentation
TabuSearch()
mh::TabuSearch::TabuSearch (const Tsp & t) inline
Constructs the Tabu Search with the problem to be solved and search parameters.
Parameters
t Is the problem to be solved.
Definition at line 34 of file TabuSearch.hpp.
 : Metaheuristic{t}, lclMax{100000}, nbrMax{40}, tabuMax{10} {}
Member Function Documentation
findOptimal()
Solution TabuSearch::findOptimal () const override virtual
Finds a near optimal solution to the problem using Tabu Search.
Returns
The optimal solution.
Implements mh::Metaheuristic.
Definition at line 21 of file TabuSearch.cpp.
{
   auto currentS = randomSolution();
   auto optimalS = currentS;
   std::list<Move> tabuList = {};
   // Main loop
   for (int i = 0; i < lclMax && !killFlag; ++i) {
     auto bestNeighbour = neighbour(currentS, generateMove(currentS, tabuList));
     // Sampling gradient to find nearly best neighbour
     for (int j = 0; j < nbrMax; ++j) {
       auto testNeighbour = neighbour(currentS, generateMove(currentS, tabuList));
       if (testNeighbour.cost < bestNeighbour.cost) {
         bestNeighbour = testNeighbour;
       }
     }
     currentS = bestNeighbour;
     // Update Tabu moves
     tabuList.push_back(currentS.moveMade);
     if (tabuList.size() > tabuMax) {
       tabuList.pop_front();
     }
     // Update optimal solution
     if (currentS.cost < optimalS.cost) {
       optimalS = currentS;
     }
   }
   return optimalS;
 }
References generateMove(), lclMax, nbrMax, mh::Metaheuristic::neighbour(), mh::Metaheuristic::randomSolution(), and tabuMax.
generateMove()
Move TabuSearch::generateMove (const Solution & s, const std::list< Move > & tabuList) const
Generates a move from the neighbourhood of a solution, that is not tabu.
Parameters
s Is the solution to generate a move for.
tabuList Is the list of forbidden moves.
Returns
The generated move.
Definition at line 10 of file TabuSearch.cpp.
{
   Move m;
   // Generate Allowed move
   do {
     m = Metaheuristic::generateMove(s);
   } while (std::find(tabuList.begin(), tabuList.end(), m) != tabuList.end());
   return m;
 }
References mh::Metaheuristic::generateMove().
Referenced by findOptimal().
The documentation for this class was generated from the following files:
TabuSearch.hpp
TabuSearch.cpp