Metaheuristics: mh::Metaheuristic Class Reference
mh::Metaheuristic Class Reference abstract
Represents a metaheuristic used to solve a problem.
#include <Metaheuristic.hpp>
Public Member Functions
Metaheuristic (const Metaheuristic &)=delete
Metaheuristic & operator= (const Metaheuristic &)=delete
virtual Solution findOptimal () const =0
Finds a near optimal solution to the problem using a metaheuristic.
Protected Member Functions
Metaheuristic (const Tsp &t)
Constructs a metaheuristic with the problem to be solved.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s) const
Applies a move to a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
std::pair< Solution, Solution > crossover (const std::vector< Solution > &p) const
Applies Uniform Order Based Crossover on parent solutions.
Private Types
using Tsp = opp::TravellingSalesmanProblem
using Solution = opp::Solution
using Move = opp::Move
Private Attributes
Tsp tsp
The problem to be solved by a metaheuristic.
Detailed Description
Represents a metaheuristic used to solve a problem.
Author
Luke Sell
Definition at line 17 of file Metaheuristic.hpp.
Constructor & Destructor Documentation
Metaheuristic()
mh::Metaheuristic::Metaheuristic (const Tsp & t) inline protected
Constructs a metaheuristic with the problem to be solved.
Parameters
t Is the problem to be solved.
Definition at line 45 of file Metaheuristic.hpp.
 : tsp{t} {}
Member Function Documentation
crossover()
std::pair<Solution, Solution> mh::Metaheuristic::crossover (const std::vector< Solution > & p) const inline protected
Applies Uniform Order Based Crossover on parent solutions.
Parameters
p Is the population used.
Returns
The pair of children generated.
Definition at line 97 of file Metaheuristic.hpp.
{
       return tsp.crossover(tsp.select(p), tsp.select(p));
     }
References opp::TravellingSalesmanProblem::crossover(), opp::TravellingSalesmanProblem::select(), and tsp.
Referenced by mh::GeneticAlgorithm::findOptimal(), and mh::MemeticAlgorithm::findOptimal().
findOptimal()
virtual Solution mh::Metaheuristic::findOptimal () const pure virtual
Finds a near optimal solution to the problem using a metaheuristic.
Returns
The optimal solution.
Implemented in mh::TabuSearch, mh::IteratedLocalSearch, mh::MemeticAlgorithm, and mh::GeneticAlgorithm.
Referenced by Logger::benchmark().
generateMove()
Move mh::Metaheuristic::generateMove (const Solution & s) const inline protected
Generates a move from the neighbourhood of a solution.
Parameters
s Is the solution to generate a move for.
Returns
The move generated.
Definition at line 54 of file Metaheuristic.hpp.
{
       return tsp.generateMove(s);
     }
References opp::TravellingSalesmanProblem::generateMove(), and tsp.
Referenced by mh::TabuSearch::generateMove().
neighbour() [1/2]
Solution mh::Metaheuristic::neighbour (const Solution & s) const inline protected
Applies a move to a solution.
Parameters
s Is the solution to apply the move to.
Returns
The neighbouring solution.
Definition at line 65 of file Metaheuristic.hpp.
{
       return tsp.neighbour(s, tsp.generateMove(s));
     }
References opp::TravellingSalesmanProblem::generateMove(), opp::TravellingSalesmanProblem::neighbour(), and tsp.
Referenced by mh::GeneticAlgorithm::findOptimal(), mh::MemeticAlgorithm::findOptimal(), mh::IteratedLocalSearch::findOptimal(), mh::TabuSearch::findOptimal(), mh::MemeticAlgorithm::localSearch(), and mh::IteratedLocalSearch::perturb().
neighbour() [2/2]
Solution mh::Metaheuristic::neighbour (const Solution & s, const Move & m) const inline protected
Applies a move to a solution.
Parameters
s Is the solution to apply the move to.
m Is the move to apply.
Returns
The neighbouring solution.
Definition at line 77 of file Metaheuristic.hpp.
{
       return tsp.neighbour(s, m);
     }
References opp::TravellingSalesmanProblem::neighbour(), and tsp.
randomSolution()
Solution mh::Metaheuristic::randomSolution () const inline protected
Generates a random solution to the problem.
Returns
The random solution.
Definition at line 86 of file Metaheuristic.hpp.
{
       return tsp.randomSolution();
     }
References opp::TravellingSalesmanProblem::randomSolution(), and tsp.
Referenced by mh::GeneticAlgorithm::findOptimal(), mh::IteratedLocalSearch::findOptimal(), mh::MemeticAlgorithm::findOptimal(), and mh::TabuSearch::findOptimal().
The documentation for this class was generated from the following file:
Metaheuristic.hpp