Metaheuristics: mh::IteratedLocalSearch Class Reference
mh::IteratedLocalSearch Class Reference
Represents the use of Iterated Local Search to solve a problem.
#include <IteratedLocalSearch.hpp>
Public Member Functions
IteratedLocalSearch (const IteratedLocalSearch &)=delete
IteratedLocalSearch & operator= (const IteratedLocalSearch &)=delete
IteratedLocalSearch (const Tsp &t)
Constructs the Iterated Local Search with the problem to be solved and search parameters.
Solution perturb (const Solution &s) const
Perturbs the solution to escape a local optima.
Solution findOptimal () const override
Finds a near optimal solution to the problem using Iterated Local Search.
Public Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Metaheuristic &)=delete
Metaheuristic & operator= (const Metaheuristic &)=delete
Private Types
using Tsp = opp::TravellingSalesmanProblem
using Solution = opp::Solution
Private Attributes
const int prtMax
The size of the perturbation to be used.
const int rstMax
The number of times the search will be restarted from the home solution.
const int lclMax
The number of times to use local search for before restarting.
Additional Inherited Members
Protected Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Tsp &t)
Constructs a metaheuristic with the problem to be solved.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s) const
Applies a move to a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
std::pair< Solution, Solution > crossover (const std::vector< Solution > &p) const
Applies Uniform Order Based Crossover on parent solutions.
Detailed Description
Represents the use of Iterated Local Search to solve a problem.
Author
Luke Sell
Definition at line 15 of file IteratedLocalSearch.hpp.
Constructor & Destructor Documentation
IteratedLocalSearch()
mh::IteratedLocalSearch::IteratedLocalSearch (const Tsp & t) inline
Constructs the Iterated Local Search with the problem to be solved and search parameters.
Parameters
t Is the problem to be solved.
Definition at line 31 of file IteratedLocalSearch.hpp.
 : Metaheuristic{t}, prtMax{2}, rstMax{300}, lclMax{20000} {}
Member Function Documentation
findOptimal()
Solution IteratedLocalSearch::findOptimal () const override virtual
Finds a near optimal solution to the problem using Iterated Local Search.
Returns
The optimal solution.
Implements mh::Metaheuristic.
Definition at line 19 of file IteratedLocalSearch.cpp.
{
   auto currentS = randomSolution();
   auto homeS = currentS;
   auto optimalS = currentS;
   // Restart loop
   for (int i = 0; i < rstMax && !killFlag; ++i) {
     // Local Search
     for (int j = 0; j < lclMax; ++j) {
       auto testNeighbour = neighbour(currentS);
       if (testNeighbour.cost < currentS.cost) {
         currentS = testNeighbour;
       }
     }
     // Update optimal solution
     if (currentS.cost < optimalS.cost) {
       optimalS = currentS;
     }
     // Update home solution
     if (currentS.cost < homeS.cost) {
       homeS = currentS;
     }
     currentS = perturb(homeS);
   }
   return optimalS;
 }
References lclMax, mh::Metaheuristic::neighbour(), perturb(), mh::Metaheuristic::randomSolution(), and rstMax.
perturb()
Solution IteratedLocalSearch::perturb (const Solution & s) const
Perturbs the solution to escape a local optima.
Parameters
s Is the solution to perturb.
Returns
The perturbed solution.
Definition at line 8 of file IteratedLocalSearch.cpp.
{
   auto currentS = s;
   // Apply perturbation
   for (int i = 0; i < prtMax; ++i) {
     currentS = neighbour(currentS);
   }
   return currentS;
 }
References mh::Metaheuristic::neighbour(), and prtMax.
Referenced by findOptimal().
The documentation for this class was generated from the following files:
IteratedLocalSearch.hpp
IteratedLocalSearch.cpp