Metaheuristics: Logger Class Reference
Logger Class Reference
Handles logging results and benchmarks to files.
#include <Logger.hpp>
Public Member Functions
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Logger (const char *f)
Creates and opens logging file with uniquely identifiable name.
void log (const opp::Solution &s)
Logs the optimal solutions returned by metaheuristics.
void log (const std::vector< Result > &w)
Logs the benchmarking data.
Result benchmark (const mh::Metaheuristic &m)
Benchmarks the metaheuristic and calculates benchmarking data.
void benchmarkAll ()
Benchmarks all metaheuristics and logs the results.
Private Attributes
const int nProblems = 5
The number of generated problems to use in the benchmarking process.
const int nRuns = 3
The number of times to run the metaheuristic on a problem to produce necessary data to calculate minimum, average and maximum values.
const int totalRuns = nProblems * nRuns
The total number of runs for each metaheuristic during the benchmarking process.
std::ofstream file
The file being logged to.
Detailed Description
Handles logging results and benchmarks to files.
Also calculates benchmarking data for logging.
Author
Luke Sell
Definition at line 38 of file Logger.hpp.
Constructor & Destructor Documentation
Logger()
Logger::Logger (const char * f) inline
Creates and opens logging file with uniquely identifiable name.
The combination of the current thread id and the current time produces an uniquely identifiable name.
Parameters
f Is the sub directory to be used.
Definition at line 53 of file Logger.hpp.
                         : file{
     std::string{
       f
       + std::to_string(
       std::hash<std::thread::id>{}(
         std::this_thread::get_id()))
       + std::to_string(
         std::chrono::system_clock::to_time_t(
           std::chrono::system_clock::now()))
       + ".log"}} {}
Member Function Documentation
benchmark()
Result Logger::benchmark (const mh::Metaheuristic & m)
Benchmarks the metaheuristic and calculates benchmarking data.
Parameters
m Is the metaheuristic to be benchmarked.
Returns
The benchmarking data.
Definition at line 46 of file Logger.cpp.
{
   int minCost = 99999;
   int avgCost = 0;
   int maxCost = 0;
   int minTime = 99999;
   int avgTime = 0;
   int maxTime = 0;
   // Calculate minimum, average and maximum values for problem
   for (int i = 0; i < nRuns; ++i) {
     auto t = std::chrono::high_resolution_clock::now();
     auto c = m.findOptimal().cost;
     auto d = std::chrono::duration_cast <
              std::chrono::duration<int, std::milli>> (
                std::chrono::high_resolution_clock::now() - t).count();
     avgCost += c;
     minCost = std::min(minCost, c);
     maxCost = std::max(maxCost, c);
     avgTime += d;
     minTime = std::min(minTime, d);
     maxTime = std::max(maxTime, d);
   }
   return {minCost, avgCost, maxCost, minTime, avgTime, maxTime};
 }
References opp::Solution::cost, mh::Metaheuristic::findOptimal(), and nRuns.
Referenced by benchmarkAll().
log() [1/2]
void Logger::log (const opp::Solution & s)
Logs the optimal solutions returned by metaheuristics.
Parameters
s Is the solution to be logged.
Definition at line 9 of file Logger.cpp.
{
   file << "Order:\n";
   for (const auto& c : s.order) {
     file << "City " << c.name << "\n";
   }
   file << "\nCost: " << s.cost << "\n" << std::endl;
 }
References opp::Solution::cost, file, and opp::Solution::order.
Referenced by benchmarkAll(), and gui::Application::update().
log() [2/2]
void Logger::log (const std::vector< Result > & w)
Logs the benchmarking data.
Parameters
w Is the benchmarking data to be logged.
Definition at line 17 of file Logger.cpp.
{
   int minCost = 99999;
   int avgCost = 0;
   int maxCost = 0;
   int minTime = 99999;
   int avgTime = 0;
   int maxTime = 0;
   // Calculate minimum, average and maximum values overall
   for (const auto& r : w) {
     avgCost += r.avgCost;
     minCost = std::min(minCost, r.minCost);
     maxCost = std::max(maxCost, r.maxCost);
     avgTime += r.avgTime;
     minTime = std::min(minTime, r.minTime);
     maxTime = std::max(maxTime, r.maxTime);
   }
   // Log benchmarking data for cost
   file << "Min Cost: " << minCost
        << "p | Avg Cost: " << avgCost / totalRuns
        << "p | Max Cost: " << maxCost << "p\n";
   // Log benchmarking data for time
   file << "Min Time: " << minTime
        << "ms | Avg Time: " << avgTime / totalRuns
        << "ms | Max Time: " << maxTime << "ms\n" << std::endl;
 }
References file, and totalRuns.
The documentation for this class was generated from the following files:
Logger.hpp
Logger.cpp