Metaheuristics: mh::MemeticAlgorithm Class Reference
mh::MemeticAlgorithm Class Reference
Represents the use of the Memetic Algorithm to solve a problem.
#include <MemeticAlgorithm.hpp>
Public Member Functions
MemeticAlgorithm (const MemeticAlgorithm &)=delete
MemeticAlgorithm & operator= (const MemeticAlgorithm &)=delete
MemeticAlgorithm (const Tsp &t)
Constructs the Memetic Algorithm with the problem to be solved and search parameters.
Solution localSearch (const Solution &s) const
Applies a local search to the solution.
Solution findOptimal () const override
Finds a near optimal solution to the problem using the Memetic Algorithm.
Public Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Metaheuristic &)=delete
Metaheuristic & operator= (const Metaheuristic &)=delete
Private Types
using Tsp = opp::TravellingSalesmanProblem
using Solution = opp::Solution
Private Attributes
const int lclMax
The number of times to use local search for.
const int genMax
The number of generations to run the Memetic Algorithm for.
const int szp
The size of the population used by the Memetic Algorithm.
Additional Inherited Members
Protected Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Tsp &t)
Constructs a metaheuristic with the problem to be solved.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s) const
Applies a move to a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
std::pair< Solution, Solution > crossover (const std::vector< Solution > &p) const
Applies Uniform Order Based Crossover on parent solutions.
Detailed Description
Represents the use of the Memetic Algorithm to solve a problem.
Author
Luke Sell
Definition at line 15 of file MemeticAlgorithm.hpp.
Constructor & Destructor Documentation
MemeticAlgorithm()
mh::MemeticAlgorithm::MemeticAlgorithm (const Tsp & t) inline
Constructs the Memetic Algorithm with the problem to be solved and search parameters.
Parameters
t Is the problem to be solved.
Definition at line 31 of file MemeticAlgorithm.hpp.
 : Metaheuristic{t}, lclMax{60}, genMax{600}, szp{300} {}
Member Function Documentation
findOptimal()
Solution MemeticAlgorithm::findOptimal () const override virtual
Finds a near optimal solution to the problem using the Memetic Algorithm.
Returns
The optimal solution.
Implements mh::Metaheuristic.
Definition at line 23 of file MemeticAlgorithm.cpp.
{
   // Generate population
   std::vector<Solution> currentP(szp);
   for (auto& s : currentP) {
     s = randomSolution();
   }
   auto optimalS = currentP[0];
   // Generation loop
   for (int i = 0; i < genMax && !killFlag; ++i) {
     // Update optimal solution
     for (auto& s : currentP) {
       // Apply local improvement
       s = localSearch(s);
       if (s.cost < optimalS.cost) {
         optimalS = s;
       }
     }
     // Generate next generation
     std::vector<Solution> nextP = {};
     for (Uint32 j = 0; j < currentP.size() / 2; ++j) {
       auto cAB = crossover(currentP);
       nextP.push_back(neighbour(cAB.first));
       nextP.push_back(neighbour(cAB.second));
     }
     currentP = nextP;
   }
   return optimalS;
 }
References mh::Metaheuristic::crossover(), genMax, localSearch(), mh::Metaheuristic::neighbour(), mh::Metaheuristic::randomSolution(), and szp.
localSearch()
Solution MemeticAlgorithm::localSearch (const Solution & s) const
Applies a local search to the solution.
Parameters
s Is the solution to apply the local search to.
Returns
The solution found by the local search.
Definition at line 9 of file MemeticAlgorithm.cpp.
{
   auto currentS = s;
   // Local Search
   for (int j = 0; j < lclMax; ++j) {
     auto testNeighbour = neighbour(currentS);
     if (testNeighbour.cost < currentS.cost) {
       currentS = testNeighbour;
     }
   }
   return currentS;
 }
References lclMax, and mh::Metaheuristic::neighbour().
Referenced by findOptimal().
The documentation for this class was generated from the following files:
MemeticAlgorithm.hpp
MemeticAlgorithm.cpp