Metaheuristics: mh::GeneticAlgorithm Class Reference
mh::GeneticAlgorithm Class Reference
Represents the use of the Genetic Algorithm to solve a problem.
#include <GeneticAlgorithm.hpp>
Public Member Functions
GeneticAlgorithm (const GeneticAlgorithm &)=delete
GeneticAlgorithm & operator= (const GeneticAlgorithm &)=delete
GeneticAlgorithm (const Tsp &t)
Constructs the Genetic Algorithm with the problem to be solved and search parameters.
Solution findOptimal () const override
Finds a near optimal solution to the problem using the Genetic Algorithm.
Public Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Metaheuristic &)=delete
Metaheuristic & operator= (const Metaheuristic &)=delete
Private Types
using Tsp = opp::TravellingSalesmanProblem
using Solution = opp::Solution
Private Attributes
const int genMax
The number of generations to run the Genetic Algorithm for.
const int szp
The size of the population used by the Genetic Algorithm.
Additional Inherited Members
Protected Member Functions inherited from mh::Metaheuristic
Metaheuristic (const Tsp &t)
Constructs a metaheuristic with the problem to be solved.
Move generateMove (const Solution &s) const
Generates a move from the neighbourhood of a solution.
Solution neighbour (const Solution &s) const
Applies a move to a solution.
Solution neighbour (const Solution &s, const Move &m) const
Applies a move to a solution.
Solution randomSolution () const
Generates a random solution to the problem.
std::pair< Solution, Solution > crossover (const std::vector< Solution > &p) const
Applies Uniform Order Based Crossover on parent solutions.
Detailed Description
Represents the use of the Genetic Algorithm to solve a problem.
Author
Luke Sell
Definition at line 15 of file GeneticAlgorithm.hpp.
Constructor & Destructor Documentation
GeneticAlgorithm()
mh::GeneticAlgorithm::GeneticAlgorithm (const Tsp & t) inline
Constructs the Genetic Algorithm with the problem to be solved and search parameters.
Parameters
t Is the problem to be solved.
Definition at line 31 of file GeneticAlgorithm.hpp.
 : Metaheuristic{t}, genMax{600}, szp{300} {}
Member Function Documentation
findOptimal()
Solution GeneticAlgorithm::findOptimal () const override virtual
Finds a near optimal solution to the problem using the Genetic Algorithm.
Returns
The optimal solution.
Implements mh::Metaheuristic.
Definition at line 9 of file GeneticAlgorithm.cpp.
{
   // Generate population
   std::vector<Solution> currentP(szp);
   for (auto& s : currentP) {
     s = randomSolution();
   }
   auto optimalS = currentP[0];
   // Generation loop
   for (int i = 0; i < genMax && !killFlag; ++i) {
     // Update optimal solution
     for (const auto& s : currentP) {
       if (s.cost < optimalS.cost) {
         optimalS = s;
       }
     }
     // Generate next generation
     std::vector<Solution> nextP = {};
     for (Uint32 j = 0; j < currentP.size() / 2; ++j) {
       auto cAB = crossover(currentP);
       nextP.push_back(neighbour(cAB.first));
       nextP.push_back(neighbour(cAB.second));
     }
     currentP = nextP;
   }
   return optimalS;
 }
References mh::Metaheuristic::crossover(), genMax, mh::Metaheuristic::neighbour(), mh::Metaheuristic::randomSolution(), and szp.
The documentation for this class was generated from the following files:
GeneticAlgorithm.hpp
GeneticAlgorithm.cpp